name: 'Test'

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: yarn
      - run: yarn build
      - run: yarn test
